export const UPDATE_SUBJECTS = "UPDATE_SUBJECTS";
export const UPDATE_HOUSES = "UPDATE_HOUSES";
export const UPDATE_CURRENT_HOUSE = "UPDATE_CURRENT_HOUSE";
export const UPDATE_WIZARD ="UPDATE_WIZARD";